---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    key_groups:
      - age:
          - "age1askn9zd7hk6lx55egwulse9t9mp5p6xptu7t7lcpuecf7577v43s39qsrl"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    key_groups:
      - age:
          - "age1askn9zd7hk6lx55egwulse9t9mp5p6xptu7t7lcpuecf7577v43s39qsrl"
stores:
  yaml:
    indent: 2
