# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:3NcfFI22SwWVFGkUa/tti1UTDoyjh0aNzGnRFoD3XnO+vf7OWYQEcg==,iv:DnYR7us20euxhMcvMaQ43csveJYYLYKZI4Plw40Rtf4=,tag:U2D4DKUe+mVrKTtPSlkLFQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1askn9zd7hk6lx55egwulse9t9mp5p6xptu7t7lcpuecf7577v43s39qsrl
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyTm9mc2dVWFBIR0RGSk41
        QWU1WWQzMEpDS0NPbmZQNENEREllT2NVRFRrCm0rZ0hhcmRZcjQvMzc0Y2hqVklO
        QXk4UEhGa0Z4ZE44TTdKM3ZRRDJFYlEKLS0tIFhaSkYvdnZjRGJpRWI5WDY2Ujcv
        ZkNSTG5JZzVnTXhjWEVnekV3eTJBcGsKaU1eQxfe1XGZnrebljgazmwH5SIoiutn
        90CiLmhY9Zu3mRRnI8enTcGg6I/alJsSHDSWBA5SLvsitNZZUMcAQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-19T19:24:02Z"
  mac: ENC[AES256_GCM,data:AngWMS08Oacnoa26KXWI3aqXO4n6yNmGrxv2vUGKppaLciZfqlBMUarNoL2VDdt/4x/cluxH3VEaB3KPPdDBbkHuVDwBPZqqR2gQi69hZk5efNubhYAcCCy3d3hmjumOhB3OLQSWfH/WrVSQqQRfWz7CTAF0oqvqskuWHQ4QSiI=,iv:fp0PGwm5buz/sbj/NwjLapXXOGURKKIlS2LvkqUI9RE=,tag:QjbCyhijo8ekIc9k6dj0Aw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
